### ISSUE TITLE
Programming Test Submission

### ISSUE THREAD

**Issue by onoffleftright** [hellofloat/float-programming-test#3]
Hey @andyburke,

I've completed the programming test and have committed the code here: https://github.com/onoffleftright/float-programming-test.

Looking forward to hearing your response on it. If you have any questions or comments for me, please let me know!

🍻 Cheers -- Jason

**Comment by andyburke** [comment]
Thanks for this submission. Unfortunately it does not pass some of our more rigorous internal tests. We've updated our repo with some more guidance on submissions that might be worth looking at.

If you'd like to take another shot, push an update to your repo and re-open this issue.

Hint: It's worth adding some additional tests to exercise some of the edge cases. We also like to see people expand the limited tests we give by default.

**Comment by onoffleftright** [comment]
@andyburke I've updated the my submission to include test coverage and implementation refactoring for the added specs in the code docs.

**Comment by onoffleftright** [comment]
Note: This repo isn't configured for, or I am missing the required permissions here to re-open the issue.

**Comment by cpuspellcaster** [comment]
@andyburke Please remove me from consideration for the position. I am no longer interested.

Thank you for your time.

**Comment by andyburke** [comment]
@onoffleftright I apologize. During the chaos of trying to launch, I somehow missed the notifications about these comments, and upon looking more carefully at how github handles issues, you are correct that once the repo owner closes an issue, you cannot reopen it.

If you withdrew yourself from consideration because I didn't reply and are still open to continuing, please restore your fork and I will take a look. If you've moved on to other opportunities, I totally understand and wish you the best of luck.

We enjoyed meeting with you and wish you the best, regardless.
